apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: templateapp
  name: aspnetcore-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templateapp
  strategy: {}
  template:
    metadata:
      labels:
        app: templateapp
    spec:
      containers:
      - image: aspnetcore-webapi-image
        imagePullPolicy: Never
        name: templateapp
        resources: {}
status: {}