apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: fullstack-template
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fullstack-template
    spec:
      containers:
      - name: rabbitmq
        image: rabbit-mq-build
        imagePullPolicy: Never
        ports:
        - containerPort: 5672