apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  selector:
    matchLabels:
      app: fullstack-template-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: fullstack-template-rabbitmq
    spec:
      containers:
      - name: producer-container
        image: producer-javascript-build
        imagePullPolicy: Never