apiVersion: v1
kind: Service
metadata:
  name: fullstack-template-rabbitmq-svc
  labels:
    app: fullstack-template-rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    nodePort: 30001
  selector:
    app: fullstack-template-rabbitmq