version: '3'

networks:
  network-rabbitmq:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - network-rabbitmq

  producer-javascript:
    image: producer-javascript-build
    networks:
      - network-rabbitmq
    depends_on:
      - "rabbitmq"
    volumes:
      - ./logs:/app/logs